/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ca.datast;

import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Home
 */
public class Book extends javax.swing.JFrame {

    /**
     * Creates new form Book
     */
    public Book() {
        initComponents();
        
        /*this.id = 0;
        this.idString = "";
        this.author = "";
        this.title = "";
        this.genre = "";
        this.available = true;*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfIdString = new javax.swing.JTextField();
        tfAuthor = new javax.swing.JTextField();
        tfTitle = new javax.swing.JTextField();
        tfGenre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        saveBookButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Book Input");

        tfIdString.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tfAuthor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tfTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tfGenre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Genre (*):");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Title:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Author:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("ID String:");

        jLabel2.setText("* If more than one genre applicable, please use | to separate each. Example: Action|Adventure|Fantasy|Romance");

        saveBookButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        saveBookButton.setText("Save book");
        saveBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBookButtonActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchButton.setText("Delete book from database");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        homeButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        homeButton.setText("Home");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfIdString, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                                    .addComponent(tfAuthor)
                                    .addComponent(tfTitle)
                                    .addComponent(tfGenre)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(saveBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(searchButton)))
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(homeButton)
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton)
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIdString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBookButton)
                    .addComponent(searchButton))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBookButtonActionPerformed
        // TODO add your handling code here:
        String idString=tfIdString.getText();
        String author=tfAuthor.getText();
        String title=tfTitle.getText();
        String genre=tfGenre.getText();
        try
        {
            FileWriter Writer=new FileWriter("C:\\Users\\Home\\Documents\\NetBeansProjects\\DataSt\\src\\main\\java\\ca\\datast\\booksdata.txt",true);
            Writer.write(""+";"+idString+";"+author+";"+title+";"+genre);
            Writer.write(System.getProperty("line.separator"));
            Writer.close();
            JOptionPane.showMessageDialog(null,"Success!");
            setVisible(false);
            new Book().setVisible(true);
                        
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null,"Error");
    }
    }//GEN-LAST:event_saveBookButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton saveBookButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField tfAuthor;
    private javax.swing.JTextField tfGenre;
    private javax.swing.JTextField tfIdString;
    private javax.swing.JTextField tfTitle;
    // End of variables declaration//GEN-END:variables

    /*private int id;
    private String idString;
    private String author;
    private String title;
    private String genre;
    private boolean available;
    

    
    public Book(int id, String idString, String author, String title, String genre, boolean available){
        this.id = id;
        this.idString = idString;
        this.author = author;    
        this.title = title;
        this.genre = genre;
        this.available = true;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getIdString() {
        return idString;
    }

    public void setIdString(String idString) {
        this.idString = idString;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getGenre() {
        return genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    public boolean isAvailable() {
        return available;
    }

    public void setAvailable(boolean available) {
        this.available = available;
    }

    
    public Book[] showBooks(String fileName){
        File file = new File(fileName);
        Book book;
        Book[] books;
        Process process = new Process();
        books = new Book[process.countLines(file)];
        try {
            FileInputStream fis = new FileInputStream(file);
            InputStreamReader isr = new InputStreamReader(fis, "UTF-8");
            BufferedReader bf = new BufferedReader(isr);
            String line;
            line=bf.readLine();
            int lines=0;
            while(true){
                line=bf.readLine();
                if(line==null)
                    break;
                String[] data=line.split(";");
                book=new Book();
                book.setId(Integer.parseInt(data[0]));
                book.setIdString(data[1]);
                book.setAuthor(data[2]);
                book.setTitle(data[3]);
                book.setGenre(data[4]);
                //book.setAvailable(Boolean.parseBoolean( data[5]);
                books[lines]=book;
                lines++;
            }
            bf.close();
        }  catch (IOException | NumberFormatException e) {
        }
        return books;
    }
     
    public int listBooks(Book[] books){
        int total=0;
        System.out.println("Scanning books");
        for (Book book : books) {
            System.out.println("Id...............................:"+book.getId());
            System.out.println("Title............................:"+book.getTitle());
            System.out.println("Author...........................:"+book.getAuthor());
            System.out.println("Genre............................:"+book.getGenre());
            System.out.println("----------------");
            total++;
        }
        return total;
    }
    
    public Book[] listAlphab(Book[] books){
        Book bookTemp;
        String a1,a2;
        for (int i = 0; i < books.length; i++) {
            for (int j = 0; j < books.length-1-i; j++) {
                a1=books[j].getTitle().trim();
                a2=books[j+1].getTitle().trim();
                if(a1.charAt(0)>a2.charAt(0)){
                    bookTemp=books[j];
                    books[j]=books[j+1];
                    books[j+1]=bookTemp;
                }
            }
        }
        return books;
    }
    
    public void listAlphabAuthor(Book[] books){
        Book bookTemp;
        String a1,a2;
        for (int i = 0; i < books.length; i++) {
            for (int j = 0; j < books.length-1-i; j++) {
                a1=books[j].getAuthor().trim();
                a2=books[j+1].getAuthor().trim();
                if(a1.charAt(0)>a2.charAt(0)){
                    bookTemp=books[j];
                    books[j]=books[j+1];
                    books[j+1]=bookTemp;
                }
            }
        }
        int t = this.listBooks(books);
    }
    
    public void listBook (Book[] books, String name){    
        for (Book book : books) {
            //buscar por títulos que tenham parte daquilo que foi digitado
            if(book.getTitle().toLowerCase().contains(name.toLowerCase())){
            System.out.println("Id...............................:"+book.getId());
            System.out.println("Title............................:"+book.getTitle());
            System.out.println("Author...........................:"+book.getAuthor());
            System.out.println("Genre............................:"+book.getGenre());
            System.out.println("----------------");
            }
            //Search by part of word typed 
            if(book.getAuthor().toLowerCase().contains(name.toLowerCase())){
                System.out.println("Id...............................:"+book.getId());
                System.out.println("Title............................:"+book.getTitle());
                System.out.println("Author...........................:"+book.getAuthor());
                System.out.println("Genre............................:"+book.getGenre());
                System.out.println("----------------");
            }
        }
        
    }
    
    public Book searchById(Book[] books, int idSearch){
        Book l = new Book();
        for (Book book : books) {
            if(book.getId()==idSearch){
                id = book.getId();
                idString = book.getIdString();
                title = book.getTitle();
                author = book.getAuthor();
                author = book.getAuthor();
                genre = book.getGenre();
                System.out.println("Id...............................:"+book.getId());
                System.out.println("IdString.........................:"+book.getIdString());
                System.out.println("Title............................:"+book.getTitle());
                System.out.println("Author...........................:"+book.getAuthor());
                System.out.println("Genre............................:"+book.getGenre());
                System.out.println("----------------");
                l.setId(id);
                l.setIdString(idString);
                l.setTitle(title);
                l.setAuthor(author);
                l.setGenre(genre);
                break;
            }
        }
        return l;
    }*/

}
